### PR TITLE
Change power connector to a barrel jack, JTAG connector and TC2030 connector

### PR DESCRIPTION
**Pull request by MuffinCutter**
I have changed a few things on the board design in order to make it cheaper and easier to build and use.
Power connector: power is now delivered trough a generic [barrel jack](https://www.aliexpress.com/item/1005001688314286.html)
JTAG connnector has been changed for a 2x5 2.54mm [pin headers](https://www.aliexpress.com/item/32910667070.html) (the smd connector was a bit pricey) [use this cable](https://www.aliexpress.com/item/4000927548547.html)
TC2030 connector: I have added the 2x3 2.54mm pin headers so you dont need to buy this [cable](https://www.tag-connect.com/product/tc2030-idc-nl) for $30+ but you can use this [cable](https://www.aliexpress.com/item/4000927548547.html)
I have also added pin description on the silkscreen for the I2C debug connector
NOTE: This has not been tested in real world.

### CODE REVIEW

**Comment by BastelPichi** [comment]
Im not sure if the barrel jack is a good idea. You never got the right cable for these. Also 3A could be problematic on these...

**Comment by skot** [comment]
This is awesome @MuffinCutter nice work!

I use barrel connectors for power on my desk for testing. They are so much easier. They do get pretty warm at 3A though. That's not good for efficiency.

This version of the bitaxe is slated for use with solar panels, in an outdoor setting. So, I think the spade connectors are the right way to go for the time being.

The tagConnect cable is cheaper when you start to do more than 30+ boards, which I'd like to be doing soon! Maybe we can figure out a way to go with one of the ultra-cheap single-row 0.1" headers?

**Comment by BastelPichi** [comment]
> I use barrel connectors for power on my desk for testing. They are so much easier. They do get pretty warm at 3A though. That's not good for efficiency.

Yeah, but connecting one up to your lab bench PSU or a 5V cable feels sooo wrong xD

**Comment by Chmeldaa** [comment]
@MuffinCutter nice update. I have noticed that in Kicad board the GND of barrel jack isn't connected to GND of board. 

Adding GND in scheme and updating the board fix the issue.

Picture of issue
 #GND

**Review by blomba29 — APPROVED** [review]

**Pull request closed without merging**
